apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  jwt-secret: "{{ .Values.backend.jwtSecret }}"
  postgres-user: "{{ .Values.postgresql.username }}"
  postgres-password: "{{ .Values.postgresql.password }}"
