apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_DB: "{{ .Values.postgresql.database }}"
  POSTGRES_USER: "{{ .Values.postgresql.username }}"
  POSTGRES_PASSWORD: "{{ .Values.postgresql.password }}"
