apiVersion: v1
kind: Service
metadata:
  name: frontend-static
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: frontend-static
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
