apiVersion: v1
kind: Service
metadata:
  name: analyzer
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: analyzer
  ports:
  - port: {{ .Values.analyzer.port }}
    targetPort: {{ .Values.analyzer.port }}
